version: '3'

services:
  app:
    container_name: app
    build: ../05/.
    user: root


  server:
    image: nginx
    container_name: server
    ports:
      - "80:8080"
    build: ../06/.
    depends_on:
      - app